#
# GitHub Action to export latest changes to en.json to https://lang.purrbot.site
#
name: "Crowdin Import GH Action"

on:
  push: # Trigger on push towards the en.json file.
    branches:
    - "master"
    paths:
    - "src/main/resources/lang/en.json"

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - name: "Update Code"
        uses: actions/Checkout@v2
      - name: "Export Crowdin Translations"
        uses: crowdin/github-action@v1.0.20
        with:
          upload_sources: true # Upload sources
          
          download_translations: false # Don't download translations from Crowdin
          skip_untranslated_files: true # Only download fully translated files
          translation: "src/main/resources/lang/%locale%.%file_extension%"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_TOKEN }}
