#
# GitHub Action to export latest changes to en.json to https://lang.purrbot.site
#
name: "Crowdin Export GH Action"

on:
  push: # Trigger on push towards the en.json file.
    branches:
    - "master"
    paths:
    - "src/main/resources/lang/en.json"

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - name: "Update Code"
        uses: actions/Checkout@v2
        
      - name: "Export Crowdin Translations"
        uses: crowdin/github-action@1.0.21
        with:
          crowdin_branch_name: 'master'
          
          upload_sources: true
          
          upload_translations: false
          download_translations: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_ID: ${{ secrets.CROWDIN_ID }}
          CROWDIN_TOKEN: ${{ secrets.CROWDIN_TOKEN }}
