name: Crowdin GH Action

on:
  schedule:
    - cron: "0/10 * * * *"

jobs:
  crowdin_sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/Checkout@v2
      - name: Sync Crowdin
        uses: crowdin/github-action@1.0.13
        with:
          # Upload the en.json to the Crowdin Project
          upload_sources: true
          source: "src/main/resources/lang/en.json"
          
          # Download the translated files
          download_translations: true
          skip_untranslated_files: true
          translation: "/src/main/resources/lang/%locale%.%file_extension%"
          
          # Push changes and create a commit for it, if not already made.
          push_translations: true
          create_pull_request: true
          commit_message: "Update %language%"
          localization_branch_name: translations
          pull_request_title: "New Crowdin translations"
          pull_request_body: "New translations have been made for the Bot."
          pull_request_labels: "Type: Translation"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_TOKEN }}
